services:
  etcd:
    build: .
    container_name: etcd-bench
    command:
      - etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://127.0.0.1:2379
    ports:
      - "2379:2379"
