// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: raftpb/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MsgUnknown  MessageType = 0 // proto3 requires a zero value
	MessageType_MsgApp      MessageType = 1
	MessageType_MsgAppResp  MessageType = 2
	MessageType_MsgVote     MessageType = 3
	MessageType_MsgVoteResp MessageType = 4
	MessageType_MsgSnap     MessageType = 5
	MessageType_MsgHup      MessageType = 6
	MessageType_MsgBeat     MessageType = 7
	MessageType_MsgProp     MessageType = 8
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MsgUnknown",
		1: "MsgApp",
		2: "MsgAppResp",
		3: "MsgVote",
		4: "MsgVoteResp",
		5: "MsgSnap",
		6: "MsgHup",
		7: "MsgBeat",
		8: "MsgProp",
	}
	MessageType_value = map[string]int32{
		"MsgUnknown":  0,
		"MsgApp":      1,
		"MsgAppResp":  2,
		"MsgVote":     3,
		"MsgVoteResp": 4,
		"MsgSnap":     5,
		"MsgHup":      6,
		"MsgBeat":     7,
		"MsgProp":     8,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_raftpb_raft_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_raftpb_raft_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_raftpb_raft_proto_rawDescGZIP(), []int{0}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_raftpb_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_raftpb_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SnapshotMeta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastIncludedIndex uint64                 `protobuf:"varint,1,opt,name=LastIncludedIndex,proto3" json:"LastIncludedIndex,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,2,opt,name=LastIncludedTerm,proto3" json:"LastIncludedTerm,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotMeta) Reset() {
	*x = SnapshotMeta{}
	mi := &file_raftpb_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMeta) ProtoMessage() {}

func (x *SnapshotMeta) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMeta.ProtoReflect.Descriptor instead.
func (*SnapshotMeta) Descriptor() ([]byte, []int) {
	return file_raftpb_raft_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotMeta) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *SnapshotMeta) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

type HardState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Term           uint64                 `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	VotedFor       uint64                 `protobuf:"varint,2,opt,name=VotedFor,proto3" json:"VotedFor,omitempty"`
	CommittedIndex uint64                 `protobuf:"varint,3,opt,name=CommittedIndex,proto3" json:"CommittedIndex,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HardState) Reset() {
	*x = HardState{}
	mi := &file_raftpb_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardState) ProtoMessage() {}

func (x *HardState) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardState.ProtoReflect.Descriptor instead.
func (*HardState) Descriptor() ([]byte, []int) {
	return file_raftpb_raft_proto_rawDescGZIP(), []int{2}
}

func (x *HardState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HardState) GetVotedFor() uint64 {
	if x != nil {
		return x.VotedFor
	}
	return 0
}

func (x *HardState) GetCommittedIndex() uint64 {
	if x != nil {
		return x.CommittedIndex
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=Type,proto3,enum=raftpb.MessageType" json:"Type,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=From,proto3" json:"From,omitempty"`
	To            uint64                 `protobuf:"varint,3,opt,name=To,proto3" json:"To,omitempty"`
	Index         uint64                 `protobuf:"varint,4,opt,name=Index,proto3" json:"Index,omitempty"`
	LogTerm       uint64                 `protobuf:"varint,5,opt,name=LogTerm,proto3" json:"LogTerm,omitempty"`
	Term          uint64                 `protobuf:"varint,6,opt,name=Term,proto3" json:"Term,omitempty"`
	Commit        uint64                 `protobuf:"varint,7,opt,name=Commit,proto3" json:"Commit,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,8,rep,name=Entries,proto3" json:"Entries,omitempty"`
	Reject        bool                   `protobuf:"varint,9,opt,name=Reject,proto3" json:"Reject,omitempty"`
	RejectHint    uint64                 `protobuf:"varint,10,opt,name=RejectHint,proto3" json:"RejectHint,omitempty"`
	Snapshot      *SnapshotMeta          `protobuf:"bytes,11,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_raftpb_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_raftpb_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_raftpb_raft_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MsgUnknown
}

func (x *Message) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Message) GetLogTerm() uint64 {
	if x != nil {
		return x.LogTerm
	}
	return 0
}

func (x *Message) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Message) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *Message) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message) GetReject() bool {
	if x != nil {
		return x.Reject
	}
	return false
}

func (x *Message) GetRejectHint() uint64 {
	if x != nil {
		return x.RejectHint
	}
	return 0
}

func (x *Message) GetSnapshot() *SnapshotMeta {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_raftpb_raft_proto protoreflect.FileDescriptor

const file_raftpb_raft_proto_rawDesc = "" +
	"\n" +
	"\x11raftpb/raft.proto\x12\x06raftpb\"E\n" +
	"\x05Entry\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\x04R\x05Index\x12\x12\n" +
	"\x04Term\x18\x02 \x01(\x04R\x04Term\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\"h\n" +
	"\fSnapshotMeta\x12,\n" +
	"\x11LastIncludedIndex\x18\x01 \x01(\x04R\x11LastIncludedIndex\x12*\n" +
	"\x10LastIncludedTerm\x18\x02 \x01(\x04R\x10LastIncludedTerm\"c\n" +
	"\tHardState\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x04R\x04Term\x12\x1a\n" +
	"\bVotedFor\x18\x02 \x01(\x04R\bVotedFor\x12&\n" +
	"\x0eCommittedIndex\x18\x03 \x01(\x04R\x0eCommittedIndex\"\xc5\x02\n" +
	"\aMessage\x12'\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x13.raftpb.MessageTypeR\x04Type\x12\x12\n" +
	"\x04From\x18\x02 \x01(\x04R\x04From\x12\x0e\n" +
	"\x02To\x18\x03 \x01(\x04R\x02To\x12\x14\n" +
	"\x05Index\x18\x04 \x01(\x04R\x05Index\x12\x18\n" +
	"\aLogTerm\x18\x05 \x01(\x04R\aLogTerm\x12\x12\n" +
	"\x04Term\x18\x06 \x01(\x04R\x04Term\x12\x16\n" +
	"\x06Commit\x18\a \x01(\x04R\x06Commit\x12'\n" +
	"\aEntries\x18\b \x03(\v2\r.raftpb.EntryR\aEntries\x12\x16\n" +
	"\x06Reject\x18\t \x01(\bR\x06Reject\x12\x1e\n" +
	"\n" +
	"RejectHint\x18\n" +
	" \x01(\x04R\n" +
	"RejectHint\x120\n" +
	"\bSnapshot\x18\v \x01(\v2\x14.raftpb.SnapshotMetaR\bSnapshot*\x8a\x01\n" +
	"\vMessageType\x12\x0e\n" +
	"\n" +
	"MsgUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06MsgApp\x10\x01\x12\x0e\n" +
	"\n" +
	"MsgAppResp\x10\x02\x12\v\n" +
	"\aMsgVote\x10\x03\x12\x0f\n" +
	"\vMsgVoteResp\x10\x04\x12\v\n" +
	"\aMsgSnap\x10\x05\x12\n" +
	"\n" +
	"\x06MsgHup\x10\x06\x12\v\n" +
	"\aMsgBeat\x10\a\x12\v\n" +
	"\aMsgProp\x10\bB\rZ\vkvgo/raftpbb\x06proto3"

var (
	file_raftpb_raft_proto_rawDescOnce sync.Once
	file_raftpb_raft_proto_rawDescData []byte
)

func file_raftpb_raft_proto_rawDescGZIP() []byte {
	file_raftpb_raft_proto_rawDescOnce.Do(func() {
		file_raftpb_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftpb_raft_proto_rawDesc), len(file_raftpb_raft_proto_rawDesc)))
	})
	return file_raftpb_raft_proto_rawDescData
}

var file_raftpb_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raftpb_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_raftpb_raft_proto_goTypes = []any{
	(MessageType)(0),     // 0: raftpb.MessageType
	(*Entry)(nil),        // 1: raftpb.Entry
	(*SnapshotMeta)(nil), // 2: raftpb.SnapshotMeta
	(*HardState)(nil),    // 3: raftpb.HardState
	(*Message)(nil),      // 4: raftpb.Message
}
var file_raftpb_raft_proto_depIdxs = []int32{
	0, // 0: raftpb.Message.Type:type_name -> raftpb.MessageType
	1, // 1: raftpb.Message.Entries:type_name -> raftpb.Entry
	2, // 2: raftpb.Message.Snapshot:type_name -> raftpb.SnapshotMeta
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_raftpb_raft_proto_init() }
func file_raftpb_raft_proto_init() {
	if File_raftpb_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftpb_raft_proto_rawDesc), len(file_raftpb_raft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raftpb_raft_proto_goTypes,
		DependencyIndexes: file_raftpb_raft_proto_depIdxs,
		EnumInfos:         file_raftpb_raft_proto_enumTypes,
		MessageInfos:      file_raftpb_raft_proto_msgTypes,
	}.Build()
	File_raftpb_raft_proto = out.File
	file_raftpb_raft_proto_goTypes = nil
	file_raftpb_raft_proto_depIdxs = nil
}
